import React from "react";
import * as actions from "../../reducer/actions/actions";
import { useSelector, useDispatch } from "react-redux";
import { stylesPanel } from "../../styles/stylesPanel";
import { green } from "@material-ui/core/colors";
import { Drawer, FormControlLabel, Switch } from "@material-ui/core";
import Thermostat from "./temperatureComponents/Thermostat";
import ChangeTemperature from "./temperatureComponents/ChangeTemperature";

export default function TemperaturePanel() {
  // gives us access to styles object generated by makeStyles
  const classes = stylesPanel();
  // gives acess to store central data
  const { eco } = useSelector((state) => state);
  // manupulated store central data
  const dispatch = useDispatch();

  const handleChange = (event) => {
    dispatch(actions.updateTemperature({ eco: event.target.checked }));
  };

  return (
    <Drawer
      classes={{
        paper: classes.drawerPaper,
      }}
      className={classes.drawer}
      variant="permanent"
      anchor="left"
    >
      <h3 className={classes.title}> Temperature Panel </h3>
      <div>
        <Thermostat
          height="300px"
          width="100%"
          numTicks={100}
          minValue={0}
          maxValue={100}
        />
        <ChangeTemperature />
      </div>
      <div className={classes.form}>
        <h3 style={{ color: green[500] }}>Eco mode</h3>
        <FormControlLabel
          control={
            <Switch
              checked={eco}
              onChange={handleChange}
              aria-label="eco switch"
            />
          }
          label={eco ? "on" : "off"}
        />
      </div>
    </Drawer>
  );
}
